### ISSUE TITLE
Send PR to PostCSS README

### ISSUE THREAD

**Issue by ai** [TCotton/postcss-mq-keyframes#4]
Add your plugin to Other section.

Note that plugins are ordered by alphabet (with special promotion for `postcss-` prefix) and links are ordered by length.

**Comment by TCotton** [comment]
okay, will do

**Comment by TCotton** [comment]
Andrey, I did a git clone of the postcss repository, made a separate branch to add a link on README file and then 'git push origin add-postcss-mq-keyframes-link' but I received a 'ERROR: Permission to postcss/postcss.git denied to TCotton' in response

**Comment by ai** [comment]
Do you clone repo directly from `github.com/postcss/postcss`?

In GitHub you need to make fork first. Open PostCSS repo and click “Fork” button on the right. Next clone your own repo, make branch and push to your repo (command will be correct, because you will have your repo in `origin`). Then open your repo and your will see new branch on top with button to make Pull Request.
